language: ruby
rvm:
  - 2.3.1
env:
  - DB=sqlite
script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec/
